### ISSUE TITLE
[DEPRECATION] HTTParty will no longer override `response#nil?`

### ISSUE THREAD

**Issue by earwickerh** [petrgazarov/keyword-crawler#1]
Hi Petr, when i run your script I'm getting: [DEPRECATION] HTTParty will no longer override `response#nil?`. This functionality will be removed in future versions. Please, add explicit check `response.body.nil? || response.body.empty?`. For more info refer to: https://github.com/jnunemaker/httparty/issues/568
 Any thoughts?

**Comment by earwickerh** [comment]
Thanks for replying. I already had, same result.  My versions:
Using concurrent-ruby 1.1.6
Using i18n 1.8.2
Using minitest 5.14.0
Using thread_safe 0.3.6
Using tzinfo 1.2.6
Using zeitwerk 2.3.0
Using activesupport 6.0.2.1
Using bundler 1.17.2
Using coderay 1.1.2
Using mime-types-data 3.2019.1009
Using mime-types 3.3.1
Using multi_xml 0.6.0
Using httparty 0.18.0
Using method_source 0.9.2
Using mini_portile2 2.4.0
Using nokogiri 1.10.9 (x64-mingw32)
Using pry 0.12.2

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by petrgazarov** [comment]
I have updated dependencies to versions that are different than those in your comment

**Comment by earwickerh** [comment]
Thanks Petr, this worked after I downgraded Ruby to <2.4 as well. However, I'm seeing only the following in the results.csv. **http://naugatuckwindowandglass.com,SUCCESS,""**.  I have multiple keywords I set in the lib/website_parser.rb. (e.g. "skylight, window"). I assumed the results.csv file would display which keywords were positively matched, but the info I see above is all I get. I expected SUCCEsS meant the site was crawled and after the comma I'd get the actual matches. Please help me understand the results when you have a moment. Thank you!

**Comment by petrgazarov** [comment]
When I run it, I get `http://naugatuckwindowandglass.com,SUCCESS,"skylight, window"` in results.csv, and my `website_parser.rb` has:

```
  KEYWORDS = [
    'skylight',
    'window'
  ]
```

My `websites.txt` is:
```
http://naugatuckwindowandglass.com
```

**Comment by earwickerh** [comment]
Gahhh, sorry. My keywords were capitalized... Worked when I lower-cased!
Superb script. Truly appreciate your help, let me know if there's anything
I can do to thank you

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by petrgazarov** [comment]
I haven't used it for a few years, so if you notice any other problems, feel free to contribute an issue or a pull request. Thanks!
